"""Docker install surface stays hashed and does not float boto3."""

from __future__ import annotations

from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]


def test_dockerfile_installs_hashed_requirements_without_extra_boto3() -> None:
    dockerfile = (_ROOT / "Dockerfile").read_text(encoding="utf-8")
    assert "pip install --no-cache-dir -r requirements.txt" in dockerfile
    assert "boto3" not in dockerfile


def test_requirements_lock_pins_boto3_with_hashes() -> None:
    lock = (_ROOT / "requirements.txt").read_text(encoding="utf-8")
    assert "boto3==" in lock
    assert "--hash=sha256:" in lock
    assert "This file is autogenerated by pip-compile" in lock
