"""Slide builders for the ``cortex_showcase`` deck — Cortex, generated by Cortex.

Every builder reads ``report["cortex_meta"]`` (see :mod:`src.cortex_meta_report`) and
emits Google Slides ``batchUpdate`` requests through the shared primitives. Builders are
defensive: when a metric is missing (e.g. a live source was unavailable at build time),
the corresponding element is omitted rather than rendered with a fabricated value.
"""

from __future__ import annotations

from typing import Any

from .slide_primitives import (
    background as _bg,
    internal_footer as _footer,
    kpi_metric_card as _kpi,
    simple_table as _table,
    slide_title as _title,
    style as _style,
)
from .slide_requests import append_slide as _slide, append_text_box as _box
from .slides_theme import (
    BLUE,
    BODY_Y,
    CONTENT_W,
    FONT,
    FONT_SERIF,
    GRAY,
    LTBLUE,
    MARGIN,
    NAVY,
    SLIDE_H,
    TEAL,
    WHITE,
)


def _meta(report: dict[str, Any]) -> dict[str, Any]:
    return report.get("cortex_meta") or {}


def _fmt(n: Any) -> str:
    """Human number: 152840 -> '152,840'; 152840 with compact flag handled by caller."""
    if isinstance(n, bool) or n is None:
        return "—"
    if isinstance(n, int):
        return f"{n:,}"
    if isinstance(n, float):
        return f"{n:,.0f}" if n == int(n) else f"{n:,.1f}"
    return str(n)


def _compact(n: Any) -> str:
    """Compact big numbers for KPI tiles: 152840 -> '153K', 1200000 -> '1.2M'."""
    if not isinstance(n, (int, float)) or isinstance(n, bool):
        return "—"
    n = float(n)
    if abs(n) >= 1_000_000:
        return f"{n / 1_000_000:.1f}M".replace(".0M", "M")
    if abs(n) >= 1_000:
        return f"{n / 1_000:.0f}K"
    return f"{int(n)}"


def _kpi_row(
    reqs: list[dict[str, Any]],
    sid: str,
    cards: list[tuple[str, str]],
    *,
    y: float,
    h: float = 74.0,
    gap: float = 12.0,
    accents: list[dict[str, float]] | None = None,
) -> None:
    """Lay out up to ~6 KPI tiles evenly across the content band."""
    n = len(cards)
    if n == 0:
        return
    w = (CONTENT_W - (n - 1) * gap) / n
    for i, (label, value) in enumerate(cards):
        x = MARGIN + i * (w + gap)
        accent = (accents[i] if accents and i < len(accents) else BLUE)
        _kpi(reqs, f"{sid}_k{i}", sid, x, y, w, h, label, value, accent=accent, value_pt=22)


def _all_customers_export(meta: dict[str, Any]) -> dict[str, Any] | None:
    """The portfolio 'all customers' export economics row, or the largest if unlabeled."""
    econ = meta.get("export_economics") or []
    if not econ:
        return None
    labeled = [e for e in econ if "all_customers" in str(e.get("artifact", "")).lower()]
    pool = labeled or econ
    return max(pool, key=lambda e: int(e.get("tokens") or 0))


def _live(meta: dict[str, Any], source: str) -> dict[str, Any]:
    block = (meta.get("live_volume") or {}).get(source) or {}
    return block if "unavailable" not in block else {}


# ── Builders ─────────────────────────────────────────────────────────────────

def cortex_title_slide(reqs: list[dict[str, Any]], sid: str, report: dict[str, Any], idx: int) -> int:
    """Cover: Cortex, built by Cortex — with a headline stat line from real metrics."""
    meta = _meta(report)
    gb = meta.get("graph_breadth") or {}
    os_ = meta.get("output_surface") or {}

    _slide(reqs, sid, idx)
    _bg(reqs, sid, NAVY)

    title = "Cortex"
    _box(reqs, f"{sid}_t", sid, MARGIN, 118, CONTENT_W, 56, title)
    _style(reqs, f"{sid}_t", 0, len(title), bold=True, size=48, color=WHITE, font=FONT_SERIF)

    sub = "The deck about Cortex — built by Cortex."
    _box(reqs, f"{sid}_s", sid, MARGIN, 182, CONTENT_W, 30, sub)
    _style(reqs, f"{sid}_s", 0, len(sub), size=18, color=LTBLUE, font=FONT)

    bits: list[str] = []
    if gb.get("data_elements"):
        bits.append(f"{_fmt(gb['data_elements'])} data elements")
    if gb.get("source_systems"):
        bits.append(f"{gb['source_systems']} source systems")
    if os_.get("slide_builders"):
        bits.append(f"{os_['slide_builders']} slide builders")
    if bits:
        line = "   ·   ".join(bits)
        _box(reqs, f"{sid}_stat", sid, MARGIN, 236, CONTENT_W, 24, line)
        _style(reqs, f"{sid}_stat", 0, len(line), size=13, color=WHITE, font=FONT)

    _footer(reqs, sid)
    return idx + 1


def cortex_overview_slide(reqs: list[dict[str, Any]], sid: str, report: dict[str, Any], idx: int) -> int:
    """What Cortex is, in numbers: breadth + output surface + (live) customers."""
    meta = _meta(report)
    gb = meta.get("graph_breadth") or {}
    os_ = meta.get("output_surface") or {}
    sf = _live(meta, "salesforce")
    book = _all_customers_export(meta)

    _slide(reqs, sid, idx)
    _title(reqs, sid, "What Cortex is, in numbers")

    cards: list[tuple[str, str]] = []
    if gb.get("data_elements"):
        cards.append(("Data elements", _fmt(gb["data_elements"])))
    if gb.get("source_systems"):
        cards.append(("Source systems", _fmt(gb["source_systems"])))
    if sf.get("portfolio_customers"):
        cards.append(("Portfolio customers", _fmt(sf["portfolio_customers"])))
    if os_.get("slide_builders"):
        cards.append(("Slide builders", _fmt(os_["slide_builders"])))
    if book and book.get("tokens"):
        # Single-token value so it never wraps in a narrow 5-up tile (unit goes in the label).
        cards.append(("Book (tokens)", _compact(book["tokens"])))
    _kpi_row(reqs, sid, cards[:5], y=BODY_Y + 10)

    lines: list[str] = []
    sor = (gb.get("system_of_record") or ["Salesforce"])[0].title()
    n_enrich = len(gb.get("enrichment_sources") or [])
    lines.append(
        f"One intelligence layer: {sor} is the system of record; {n_enrich} sources enrich it. "
        f"{_fmt(gb.get('report_blobs_mapped'))} report blobs feed the model."
    )
    lines.append(
        f"Two outputs, one pipeline: an LLM-queryable context export and "
        f"{_fmt(os_.get('slide_builders'))} slide builders across "
        f"{_fmt(os_.get('slide_builder_modules'))} modules that auto-write the decks."
    )
    y = BODY_Y + 110
    for i, ln in enumerate(lines):
        _box(reqs, f"{sid}_ln{i}", sid, MARGIN, y, CONTENT_W, 40, f"•  {ln}")
        _style(reqs, f"{sid}_ln{i}", 0, len(ln) + 3, size=13, color=NAVY, font=FONT)
        y += 44
    return idx + 1


def cortex_graph_breadth_slide(reqs: list[dict[str, Any]], sid: str, report: dict[str, Any], idx: int) -> int:
    """One graph, N systems, one system of record — with report-blobs-per-source."""
    meta = _meta(report)
    gb = meta.get("graph_breadth") or {}

    _slide(reqs, sid, idx)
    _title(reqs, sid, "One graph, one system of record")

    sor = ", ".join(s.title() for s in (gb.get("system_of_record") or []))
    enrich = gb.get("enrichment_sources") or []
    intro = (
        f"{sor} is authoritative for who is a customer and churn/ARR. "
        f"{len(enrich)} enrichment sources ({', '.join(enrich)}) add usage, support, engineering, "
        "and AI-coding signal — but never override the system of record."
    )
    _box(reqs, f"{sid}_intro", sid, MARGIN, BODY_Y + 4, CONTENT_W, 54, intro)
    _style(reqs, f"{sid}_intro", 0, len(intro), size=12, color=NAVY, font=FONT)

    per = gb.get("report_blobs_per_source") or {}
    if per:
        rows = [[src, str(count)] for src, count in list(per.items())[:8]]
        hdr = "Report blobs per source"
        _box(reqs, f"{sid}_th", sid, MARGIN, BODY_Y + 66, CONTENT_W, 18, hdr)
        _style(reqs, f"{sid}_th", 0, len(hdr), bold=True, size=12, color=NAVY, font=FONT_SERIF)
        _table(
            reqs, f"{sid}_tbl", sid, MARGIN, BODY_Y + 88,
            col_widths=[220.0, 120.0], row_h=20.0,
            headers=["Source", "Report blobs"], rows=rows,
        )
    return idx + 1


def cortex_dogfood_slide(reqs: list[dict[str, Any]], sid: str, report: dict[str, Any], idx: int) -> int:
    """Live: the AI-assisted engineering team that built Cortex (Jira, GitHub, Cursor)."""
    meta = _meta(report)
    jira = _live(meta, "jira_engineering")
    gh = _live(meta, "github")
    cursor = _live(meta, "cursor")
    window = jira.get("window_days") or (meta.get("live_volume") or {}).get("window_days") or 30

    _slide(reqs, sid, idx)
    _title(reqs, sid, f"The team that built Cortex — measured by Cortex (last {window}d)")

    if jira:
        cards = [
            ("In-flight tickets", _fmt(jira.get("in_flight_tickets"))),
            ("Closed", _fmt(jira.get("closed_tickets_window"))),
            ("Contributors", _fmt(jira.get("contributors"))),
            ("Open bugs", _fmt(jira.get("open_bugs"))),
            ("Blockers/criticals", _fmt(jira.get("blockers_criticals"))),
        ]
        accents = [BLUE, TEAL, BLUE, BLUE, NAVY]
        _kpi_row(reqs, sid, cards, y=BODY_Y + 10, accents=accents)
        caption = "Live from the same engineering-portfolio pipeline every deck uses (Jira LEAN)."
    else:
        caption = (
            "Jira engineering counts unavailable at build time — run in the deploy env with "
            "Jira creds to populate this slide."
        )

    extra: list[str] = []
    if gh:
        extra.append(
            f"GitHub: {_fmt(gh.get('commits_window'))} commits, "
            f"{_fmt(gh.get('merged_prs_window'))} merged PRs across {_fmt(gh.get('repos'))} repos."
        )
    if cursor:
        spend = cursor.get("spend_usd_cycle")
        extra.append(
            f"Cursor: {_fmt(cursor.get('seats'))} seats, "
            f"{_compact(cursor.get('total_tokens_window'))} tokens"
            + (f", ${_fmt(spend)} spend this cycle." if spend is not None else ".")
        )

    y = BODY_Y + 100
    _box(reqs, f"{sid}_cap", sid, MARGIN, y, CONTENT_W, 20, caption)
    _style(reqs, f"{sid}_cap", 0, len(caption), size=11, color=GRAY, font=FONT, italic=True)
    y += 26
    for i, ln in enumerate(extra):
        _box(reqs, f"{sid}_ex{i}", sid, MARGIN, y, CONTENT_W, 20, f"•  {ln}")
        _style(reqs, f"{sid}_ex{i}", 0, len(ln) + 3, size=12, color=NAVY, font=FONT)
        y += 24
    return idx + 1


def cortex_economics_slide(reqs: list[dict[str, Any]], sid: str, report: dict[str, Any], idx: int) -> int:
    """Engineered for the model: the whole book of business fits in one context window."""
    meta = _meta(report)
    budget = meta.get("token_budget")
    book = _all_customers_export(meta)
    sf = _live(meta, "salesforce")

    _slide(reqs, sid, idx)
    _title(reqs, sid, "Engineered for the model: the whole book in one prompt")

    cards: list[tuple[str, str]] = []
    if budget:
        cards.append(("Token budget", _compact(budget)))
    if book and book.get("tokens"):
        pct = book.get("pct_of_budget")
        cards.append(("Book of business", f"{_compact(book['tokens'])}" + (f" ({pct}%)" if pct else "")))
    customers = sf.get("portfolio_customers")
    if book and book.get("tokens") and customers:
        per_cust = int(round(book["tokens"] / customers))
        cards.append(("Tokens / customer", _fmt(per_cust)))
    if cards:
        _kpi_row(reqs, sid, cards, y=BODY_Y + 10)

    bullets = [
        "We size the export to the model as reader — a token budget, not a byte cap.",
        "Merged the 3× CS-Report factory duplication; key-shortening trimmed ~19%.",
        "Markdown tables over nested JSON cut the summary layer ~43% and read cleaner.",
    ]
    y = BODY_Y + (100 if cards else 10)
    for i, ln in enumerate(bullets):
        _box(reqs, f"{sid}_b{i}", sid, MARGIN, y, CONTENT_W, 22, f"•  {ln}")
        _style(reqs, f"{sid}_b{i}", 0, len(ln) + 3, size=12, color=NAVY, font=FONT)
        y += 26

    if book and book.get("tokens") and customers:
        punch = (
            f"{_fmt(customers)} customers → {_fmt(book['tokens'])} tokens "
            f"≈ {_fmt(int(round(book['tokens'] / customers)))} tokens each. The whole book, one prompt away."
        )
        _box(reqs, f"{sid}_p", sid, MARGIN, SLIDE_H - 54, CONTENT_W, 22, punch)
        _style(reqs, f"{sid}_p", 0, len(punch), bold=True, size=12, color=BLUE, font=FONT)
    return idx + 1
